/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 0c916ff6cad06871bec0592ffd1b1aa2)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_ALLOWED_EMAILS: string;
	GOOGLE_REDIRECT_URI: string;
}
declare namespace Cloudflare {
	interface StagingEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_ALLOWED_EMAILS: string;
		GOOGLE_REDIRECT_URI: string;
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_ALLOWED_EMAILS: string;
		GOOGLE_REDIRECT_URI: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_ALLOWED_EMAILS" | "GOOGLE_REDIRECT_URI">> {}
}
